### ISSUE TITLE
Questions about your work.

### ISSUE THREAD

**Issue by magnusmagellan** [michaeldzjap/Kaplan-Advanced-Calculus-Solutions#1]
Hello sir. Great work you have done in the book's solutions.May I ask you a few questions?

1 - How did you manage to write all of this using Latex? Did it  take much of your time writing/fixing the content?

2- Which software did you use to graph in 3D and 2D?

3- Which books or sites do you recommend/suggest to grasp the content in this book?

Best regards, Raylsson Magalhães.

**Comment by michaeldzjap** [comment]
Hey Raylsson,

1. It does take some time to write. It is purely a hobby project I work on when I have time, so there is no pressure for me to finish something before a given date. I use [Overleaf](https://www.overleaf.com/), which makes it quite easy to manage this project LaTeX wise.

2. Various free online software tools like
    - https://academo.org/demos/3d-surface-plotter/
    - http://grapher.mathpix.com/
    - https://www.desmos.com/calculator
    - https://www.monroecc.edu/faculty/paulseeburger/calcnsf/CalcPlot3D/
    - https://technology.cpm.org/general/3dgraph/

3. That is quite a hard question to answer actually. I mostly use the book content itself to do the exercises and to understand the discussed topics. Usually that is enough for me. Sometimes the book is a bit unclear and so it is quite challenging to understand exactly what is asked of you in an exercise. Then I might do a Google search on a specific topic in order to find more clear explanations or examples. I couldn't really recommend you a specific site or book though. When I started learning calculus many years ago I used [Thomas' Calculus](https://www.pearson.com/store/p/thomas-calculus/P100002443256) and I quite liked it, but it doesn't really cover more advanced matters.
